remote: true

experienceLevel:
 internship: false
 entry: false
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: true
 24 hours: true

positions:
  - Java Developer
  - C# Developer
  - ASP.Net Developer
  - Backend Developer

locations:
  - United States
  - Boston

apply_once_at_company: true

distance: 100

companyBlacklist:
  - chewy
  - Infosys

titleBlacklist:
  - node
  - nodejs
  - scala
  - go

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'